# SOPS configuration for age encryption
# This file tells SOPS which keys to use for encryption/decryption

creation_rules:
  # Rule for all YAML files in secrets directory
  - path_regex: secrets/.*\.yaml$
    age: age16pa9tevkpr7xu4jmlqq6mykrxds3y8rfcqy6u2dgwuas2jztl32qrqqpey

  # Rule for all JSON files in secrets directory
  - path_regex: secrets/.*\.json$
    age: age16pa9tevkpr7xu4jmlqq6mykrxds3y8rfcqy6u2dgwuas2jztl32qrqqpey

  # Rule for all ENV files in secrets directory
  - path_regex: secrets/.*\.env$
    age: age16pa9tevkpr7xu4jmlqq6mykrxds3y8rfcqy6u2dgwuas2jztl32qrqqpey